# Crypto Analysis
Load and clean the daily snapshot data.

In [19]:
from pathlib import Path
import pandas as pd

# Resolve project root regardless of where Jupyter sets the working directory
_cwd = Path().resolve()
BASE_DIR = _cwd if (_cwd / 'output').exists() else _cwd.parent

df = pd.read_csv(BASE_DIR / 'output/raw/crypto_daily_snapshots.csv', encoding='utf-8-sig')
df

,timestamp,symbol,id,name,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,...,global_derivatives_volume_24h,global_derivatives_volume_24h_reported,global_derivatives_24h_percentage_change,global_total_crypto_dex_currencies,global_today_incremental_crypto_number,global_past_24h_incremental_crypto_number,global_past_7d_incremental_crypto_number,global_past_30d_incremental_crypto_number,global_today_change_percent,global_last_updated
0,2026-03-04 15:17:25.859452,BTC,1,Bitcoin,bitcoin,12570,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19997556.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
1,2026-03-04 15:17:25.859452,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692150.42008,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
2,2026-03-04 15:17:25.859452,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358610.77000,136358607.97000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
3,2026-03-04 15:17:25.859452,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569767412.47295,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
4,2026-03-04 15:17:25.859452,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
5,2026-03-04 15:17:25.859452,DOGE,74,Dogecoin,dogecoin,1406,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,168976693126.57907,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
6,2026-03-04 15:17:25.859452,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
7,2026-03-04 15:17:25.859452,TRX,1958,TRON,tron,1304,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94741680902.06120,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
8,2026-03-04 15:17:25.859452,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
9,2026-03-04 15:17:25.859452,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452742484.70281,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
10,2026-03-04 15:17:25.859452,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
11,2026-03-04 15:17:25.859452,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
12,2026-03-04 15:17:25.859452,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671149579.01020,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
13,2026-03-04 15:17:25.859452,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10601927073.04602,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
14,2026-03-04 15:17:25.859452,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76911876.98347,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
15,2026-03-04 15:17:25.859452,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20002471.87500,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
16,2026-03-04 15:17:25.859452,UNI,7083,Uniswap,uniswap,1411,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633795562.74653,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
17,2026-03-04 15:17:25.859452,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289252866.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
18,2026-03-04 15:17:25.859452,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985091890.39495,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
19,2026-03-04 15:17:25.859452,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496027140.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
20,2026-03-04 15:33:37.459146,BTC,1,Bitcoin,bitcoin,12570,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19997556.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
21,2026-03-04 15:33:37.459146,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692150.42008,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
22,2026-03-04 15:33:37.459146,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358607.97000,136358607.97000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
23,2026-03-04 15:33:37.459146,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569767412.47295,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
24,2026-03-04 15:33:37.459146,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
25,2026-03-04 15:33:37.459146,DOGE,74,Dogecoin,dogecoin,1406,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,168976693126.57907,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
26,2026-03-04 15:33:37.459146,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
27,2026-03-04 15:33:37.459146,TRX,1958,TRON,tron,1304,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94741680902.06120,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
28,2026-03-04 15:33:37.459146,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
29,2026-03-04 15:33:37.459146,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452742484.70281,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
30,2026-03-04 15:33:37.459146,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
31,2026-03-04 15:33:37.459146,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
32,2026-03-04 15:33:37.459146,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671149579.01020,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
33,2026-03-04 15:33:37.459146,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10601927073.04602,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
34,2026-03-04 15:33:37.459146,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76911876.98347,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
35,2026-03-04 15:33:37.459146,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20002471.87500,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
36,2026-03-04 15:33:37.459146,UNI,7083,Uniswap,uniswap,1411,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633795562.74653,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
37,2026-03-04 15:33:37.459146,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289252866.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
38,2026-03-04 15:33:37.459146,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985091890.39495,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
39,2026-03-04 15:33:37.459146,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496027140.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
40,2026-03-05 21:11:25.610511,BTC,1,Bitcoin,bitcoin,12571,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19998093.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
41,2026-03-05 21:11:25.610511,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692108.97550,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
42,2026-03-05 21:11:25.610511,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358541.80000,136358541.80000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
43,2026-03-05 21:11:25.610511,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569763750.35215,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
44,2026-03-05 21:11:25.610511,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
45,2026-03-05 21:11:25.610511,DOGE,74,Dogecoin,dogecoin,1407,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,153281356383.70526,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
46,2026-03-05 21:11:25.610511,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
47,2026-03-05 21:11:25.610511,TRX,1958,TRON,tron,1305,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94742233291.64661,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
48,2026-03-05 21:11:25.610511,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
49,2026-03-05 21:11:25.610511,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452840181.38496,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
50,2026-03-05 21:11:25.610511,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
51,2026-03-05 21:11:25.610511,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
52,2026-03-05 21:11:25.610511,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671583119.10533,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
53,2026-03-05 21:11:25.610511,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10602502283.19926,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
54,2026-03-05 21:11:25.610511,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76916283.23347,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
55,2026-03-05 21:11:25.610511,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20003034.37500,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
56,2026-03-05 21:11:25.610511,UNI,7083,Uniswap,uniswap,1412,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633755562.74653,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
57,2026-03-05 21:11:25.610511,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289383171.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
58,2026-03-05 21:11:25.610511,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985990215.50566,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
59,2026-03-05 21:11:25.610511,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496198300.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z

In [20]:
df = df.drop_duplicates(subset=['timestamp', 'symbol'], keep = 'first')

In [21]:
df

,timestamp,symbol,id,name,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,...,global_derivatives_volume_24h,global_derivatives_volume_24h_reported,global_derivatives_24h_percentage_change,global_total_crypto_dex_currencies,global_today_incremental_crypto_number,global_past_24h_incremental_crypto_number,global_past_7d_incremental_crypto_number,global_past_30d_incremental_crypto_number,global_today_change_percent,global_last_updated
0,2026-03-04 15:17:25.859452,BTC,1,Bitcoin,bitcoin,12570,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19997556.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
1,2026-03-04 15:17:25.859452,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692150.42008,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
2,2026-03-04 15:17:25.859452,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358610.77000,136358607.97000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
3,2026-03-04 15:17:25.859452,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569767412.47295,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
4,2026-03-04 15:17:25.859452,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
5,2026-03-04 15:17:25.859452,DOGE,74,Dogecoin,dogecoin,1406,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,168976693126.57907,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
6,2026-03-04 15:17:25.859452,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
7,2026-03-04 15:17:25.859452,TRX,1958,TRON,tron,1304,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94741680902.06120,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
8,2026-03-04 15:17:25.859452,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
9,2026-03-04 15:17:25.859452,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452742484.70281,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
10,2026-03-04 15:17:25.859452,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
11,2026-03-04 15:17:25.859452,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
12,2026-03-04 15:17:25.859452,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671149579.01020,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
13,2026-03-04 15:17:25.859452,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10601927073.04602,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
14,2026-03-04 15:17:25.859452,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76911876.98347,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
15,2026-03-04 15:17:25.859452,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20002471.87500,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
16,2026-03-04 15:17:25.859452,UNI,7083,Uniswap,uniswap,1411,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633795562.74653,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
17,2026-03-04 15:17:25.859452,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289252866.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
18,2026-03-04 15:17:25.859452,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985091890.39495,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
19,2026-03-04 15:17:25.859452,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496027140.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
20,2026-03-04 15:33:37.459146,BTC,1,Bitcoin,bitcoin,12570,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19997556.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
21,2026-03-04 15:33:37.459146,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692150.42008,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
22,2026-03-04 15:33:37.459146,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358607.97000,136358607.97000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
23,2026-03-04 15:33:37.459146,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569767412.47295,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
24,2026-03-04 15:33:37.459146,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
25,2026-03-04 15:33:37.459146,DOGE,74,Dogecoin,dogecoin,1406,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,168976693126.57907,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
26,2026-03-04 15:33:37.459146,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
27,2026-03-04 15:33:37.459146,TRX,1958,TRON,tron,1304,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94741680902.06120,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
28,2026-03-04 15:33:37.459146,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
29,2026-03-04 15:33:37.459146,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452742484.70281,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
30,2026-03-04 15:33:37.459146,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
31,2026-03-04 15:33:37.459146,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
32,2026-03-04 15:33:37.459146,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671149579.01020,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
33,2026-03-04 15:33:37.459146,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10601927073.04602,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
34,2026-03-04 15:33:37.459146,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76911876.98347,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
35,2026-03-04 15:33:37.459146,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20002471.87500,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
36,2026-03-04 15:33:37.459146,UNI,7083,Uniswap,uniswap,1411,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633795562.74653,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
37,2026-03-04 15:33:37.459146,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289252866.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
38,2026-03-04 15:33:37.459146,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985091890.39495,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
39,2026-03-04 15:33:37.459146,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496027140.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
40,2026-03-05 21:11:25.610511,BTC,1,Bitcoin,bitcoin,12571,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19998093.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
41,2026-03-05 21:11:25.610511,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692108.97550,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
42,2026-03-05 21:11:25.610511,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358541.80000,136358541.80000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
43,2026-03-05 21:11:25.610511,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569763750.35215,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
44,2026-03-05 21:11:25.610511,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
45,2026-03-05 21:11:25.610511,DOGE,74,Dogecoin,dogecoin,1407,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,153281356383.70526,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
46,2026-03-05 21:11:25.610511,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
47,2026-03-05 21:11:25.610511,TRX,1958,TRON,tron,1305,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94742233291.64661,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
48,2026-03-05 21:11:25.610511,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
49,2026-03-05 21:11:25.610511,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452840181.38496,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
50,2026-03-05 21:11:25.610511,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
51,2026-03-05 21:11:25.610511,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
52,2026-03-05 21:11:25.610511,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671583119.10533,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
53,2026-03-05 21:11:25.610511,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10602502283.19926,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
54,2026-03-05 21:11:25.610511,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76916283.23347,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
55,2026-03-05 21:11:25.610511,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20003034.37500,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
56,2026-03-05 21:11:25.610511,UNI,7083,Uniswap,uniswap,1412,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633755562.74653,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
57,2026-03-05 21:11:25.610511,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289383171.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
58,2026-03-05 21:11:25.610511,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985990215.50566,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
59,2026-03-05 21:11:25.610511,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496198300.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z

In [22]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)
df

,timestamp,symbol,id,name,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,...,global_derivatives_volume_24h,global_derivatives_volume_24h_reported,global_derivatives_24h_percentage_change,global_total_crypto_dex_currencies,global_today_incremental_crypto_number,global_past_24h_incremental_crypto_number,global_past_7d_incremental_crypto_number,global_past_30d_incremental_crypto_number,global_today_change_percent,global_last_updated
0,2026-03-04 15:17:25.859452,BTC,1,Bitcoin,bitcoin,12570,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19997556.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
1,2026-03-04 15:17:25.859452,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692150.42008,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
2,2026-03-04 15:17:25.859452,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358610.77000,136358607.97000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
3,2026-03-04 15:17:25.859452,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569767412.47295,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
4,2026-03-04 15:17:25.859452,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
5,2026-03-04 15:17:25.859452,DOGE,74,Dogecoin,dogecoin,1406,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,168976693126.57907,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
6,2026-03-04 15:17:25.859452,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
7,2026-03-04 15:17:25.859452,TRX,1958,TRON,tron,1304,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94741680902.06120,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
8,2026-03-04 15:17:25.859452,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
9,2026-03-04 15:17:25.859452,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452742484.70281,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
10,2026-03-04 15:17:25.859452,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
11,2026-03-04 15:17:25.859452,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
12,2026-03-04 15:17:25.859452,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671149579.01020,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
13,2026-03-04 15:17:25.859452,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10601927073.04602,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
14,2026-03-04 15:17:25.859452,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76911876.98347,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
15,2026-03-04 15:17:25.859452,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20002471.87500,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
16,2026-03-04 15:17:25.859452,UNI,7083,Uniswap,uniswap,1411,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633795562.74653,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
17,2026-03-04 15:17:25.859452,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289252866.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
18,2026-03-04 15:17:25.859452,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985091890.39495,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
19,2026-03-04 15:17:25.859452,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496027140.00000,...,1081072494741.13416,1118700706503.75977,3.91884,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:14:59.999Z
20,2026-03-04 15:33:37.459146,BTC,1,Bitcoin,bitcoin,12570,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19997556.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
21,2026-03-04 15:33:37.459146,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692150.42008,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
22,2026-03-04 15:33:37.459146,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358607.97000,136358607.97000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
23,2026-03-04 15:33:37.459146,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569767412.47295,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
24,2026-03-04 15:33:37.459146,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
25,2026-03-04 15:33:37.459146,DOGE,74,Dogecoin,dogecoin,1406,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,168976693126.57907,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
26,2026-03-04 15:33:37.459146,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
27,2026-03-04 15:33:37.459146,TRX,1958,TRON,tron,1304,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94741680902.06120,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
28,2026-03-04 15:33:37.459146,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
29,2026-03-04 15:33:37.459146,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452742484.70281,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
30,2026-03-04 15:33:37.459146,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
31,2026-03-04 15:33:37.459146,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
32,2026-03-04 15:33:37.459146,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671149579.01020,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
33,2026-03-04 15:33:37.459146,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10601927073.04602,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
34,2026-03-04 15:33:37.459146,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76911876.98347,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
35,2026-03-04 15:33:37.459146,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20002471.87500,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
36,2026-03-04 15:33:37.459146,UNI,7083,Uniswap,uniswap,1411,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633795562.74653,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
37,2026-03-04 15:33:37.459146,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289252866.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
38,2026-03-04 15:33:37.459146,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985091890.39495,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
39,2026-03-04 15:33:37.459146,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496027140.00000,...,1083701578301.22717,1120534527335.34839,4.18597,36775057,1,167385,988856,4727413,0.00008,2026-03-04T04:30:59.999Z
40,2026-03-05 21:11:25.610511,BTC,1,Bitcoin,bitcoin,12571,2010-07-13T00:00:00.000Z,mineable|pow|sha-256|store-of-value|state-chan...,21000000.00000,19998093.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
41,2026-03-05 21:11:25.610511,ETH,1027,Ethereum,ethereum,11608,2015-08-07T00:00:00.000Z,pos|smart-contracts|ethereum-ecosystem|coinbas...,NaN,120692108.97550,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
42,2026-03-05 21:11:25.610511,BNB,1839,BNB,bnb,3140,2017-07-25T00:00:00.000Z,marketplace|centralized-exchange|payments|smar...,136358541.80000,136358541.80000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
43,2026-03-05 21:11:25.610511,SOL,5426,Solana,solana,1094,2020-04-10T00:00:00.000Z,pos|platform|solana-ecosystem|cms-holdings-por...,NaN,569763750.35215,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
44,2026-03-05 21:11:25.610511,XRP,52,XRP,xrp,1804,2013-08-04T00:00:00.000Z,medium-of-exchange|enterprise-solutions|xrp-ec...,100000000000.00000,61090376977.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
45,2026-03-05 21:11:25.610511,DOGE,74,Dogecoin,dogecoin,1407,2013-12-15T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|memes|p...,NaN,153281356383.70526,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
46,2026-03-05 21:11:25.610511,ADA,2010,Cardano,cardano,1686,2017-10-01T00:00:00.000Z,dpos|pos|platform|research|smart-contracts|sta...,45000000000.00000,36078864112.21547,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
47,2026-03-05 21:11:25.610511,TRX,1958,TRON,tron,1305,2017-09-13T00:00:00.000Z,media|payments|tron-ecosystem|layer-1|dwf-labs...,NaN,94742233291.64661,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
48,2026-03-05 21:11:25.610511,AVAX,5805,Avalanche,avalanche,1061,2020-07-13T00:00:00.000Z,smart-contracts|three-arrows-capital-portfolio...,715748719.00000,431771961.17721,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
49,2026-03-05 21:11:25.610511,TON,11419,Toncoin,toncoin,857,2021-08-26T13:40:22.000Z,pos|layer-1|ftx-bankruptcy-estate|dwf-labs-por...,NaN,2452840181.38496,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
50,2026-03-05 21:11:25.610511,LINK,1975,Chainlink,chainlink,2215,2017-09-20T00:00:00.000Z,platform|cosmos-ecosystem|defi|privacy|interop...,1000000000.00000,708099970.45259,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
51,2026-03-05 21:11:25.610511,SHIB,5994,Shiba Inu,shiba-inu,1045,2020-08-01T00:00:00.000Z,memes|ethereum-ecosystem|doggone-doggerel|bnb-...,589552695333683.00000,589243742059209.87500,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
52,2026-03-05 21:11:25.610511,DOT,6636,Polkadot,polkadot-new,1029,2020-08-19T00:00:00.000Z,defi|ethereum-ecosystem|substrate|polkadot|pol...,2100000000.00000,1671583119.10533,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
53,2026-03-05 21:11:25.610511,POL,28321,Polygon (prev. MATIC),polygon-ecosystem-token,632,2023-10-30T14:43:57.000Z,ethereum-ecosystem|layer-2|polygon-ecosystem|b...,NaN,10602502283.19926,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
54,2026-03-05 21:11:25.610511,LTC,2,Litecoin,litecoin,1510,2013-04-28T00:00:00.000Z,mineable|pow|scrypt|medium-of-exchange|privacy...,84000000.00000,76916283.23347,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
55,2026-03-05 21:11:25.610511,BCH,1831,Bitcoin Cash,bitcoin-cash,1140,2017-07-23T00:00:00.000Z,mineable|pow|sha-256|marketplace|medium-of-exc...,21000000.00000,20003034.37500,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
56,2026-03-05 21:11:25.610511,UNI,7083,Uniswap,uniswap,1412,2020-09-17T00:00:00.000Z,decentralized-exchange-dex-token|defi|dao|ethe...,NaN,633755562.74653,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
57,2026-03-05 21:11:25.610511,NEAR,6535,NEAR Protocol,near-protocol,621,2020-08-11T00:00:00.000Z,platform|ai-big-data|staking|coinbase-ventures...,NaN,1289383171.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
58,2026-03-05 21:11:25.610511,XLM,512,Stellar,stellar,807,2014-08-05T00:00:00.000Z,medium-of-exchange|enterprise-solutions|decent...,50001806812.00000,32985990215.50566,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z
59,2026-03-05 21:11:25.610511,ATOM,3794,Cosmos,cosmos,962,2019-03-14T00:00:00.000Z,platform|cosmos-ecosystem|communications-socia...,NaN,496198300.00000,...,1126200969683.01538,1168719674889.25513,-3.34108,36898967,0,123930,966253,4710859,0.00004,2026-03-05T10:08:59.999Z

In [23]:
print(df[['timestamp', 'last_updated', 'aud_last_updated']].dtypes)

timestamp           str
last_updated        str
aud_last_updated    str
dtype: object

In [24]:
df2 = df[['timestamp', 'id', 'symbol', 'name', 'slug', 'cmc_rank', 'date_added', 
        'max_supply', 'circulating_supply', 'total_supply', 'infinite_supply', 
        'last_updated', 'aud_price','aud_volume_24h', 
       'aud_cex_volume_24h', 'aud_dex_volume_24h','aud_volume_change_24h', 
       'aud_percent_change_1h', 'aud_percent_change_24h', 'aud_percent_change_7d',
       'aud_percent_change_30d', 'aud_percent_change_60d', 'aud_percent_change_90d', 
       'aud_market_cap', 'aud_market_cap_dominance', 'aud_fully_diluted_market_cap', 
       'global_eth_dominance', 'global_btc_dominance', 'global_defi_volume_24h', 
       'global_defi_market_cap', 'global_stablecoin_volume_24h', 
       'global_stablecoin_market_cap', 'global_derivatives_volume_24h']].copy()

In [25]:
len(df2.columns)

33

In [26]:
df2['timestamp'] = pd.to_datetime(df2['timestamp'])
df2['last_updated'] = pd.to_datetime(df2['last_updated'])
df2['date_added'] = pd.to_datetime(df2['date_added'])

print(df2[['timestamp', 'last_updated', 'date_added']].dtypes)

timestamp            datetime64[us]
last_updated    datetime64[us, UTC]
date_added      datetime64[us, UTC]
dtype: object

In [27]:
print(df2.dtypes)

timestamp                             datetime64[us]
id                                             int64
symbol                                           str
name                                             str
slug                                             str
cmc_rank                                       int64
date_added                       datetime64[us, UTC]
max_supply                                   float64
circulating_supply                           float64
total_supply                                 float64
infinite_supply                                 bool
last_updated                     datetime64[us, UTC]
aud_price                                    float64
aud_volume_24h                               float64
aud_cex_volume_24h                           float64
aud_dex_volume_24h                           float64
aud_volume_change_24h                        float64
aud_percent_change_1h                        float64
aud_percent_change_24h                       float64
aud_percent_change_7d                        float64
aud_percent_change_30d                       float64
aud_percent_change_60d                       float64
aud_percent_change_90d                       float64
aud_market_cap                               float64
aud_market_cap_dominance                     float64
aud_fully_diluted_market_cap                 float64
global_eth_dominance                         float64
global_btc_dominance                         float64
global_defi_volume_24h                       float64
global_defi_market_cap                       float64
global_stablecoin_volume_24h                 float64
global_stablecoin_market_cap                 float64
global_derivatives_volume_24h                float64
dtype: object

In [28]:
df2['id'] = df2['id'].astype(int)
df2['cmc_rank'] = df2['cmc_rank'].astype(int)

In [29]:
df2['date'] = pd.to_datetime(df2['timestamp']).dt.normalize()
print(df2['date'].dtype)

datetime64[us]

In [30]:
dim_coin = df2[['id', 'symbol', 'name', 'slug', 'date_added',  'max_supply', 'infinite_supply']].copy()
dim_coin = dim_coin.drop_duplicates(subset=['id'], keep='first')

In [31]:
dim_coin

,id,symbol,name,slug,date_added,max_supply,infinite_supply
0,1,BTC,Bitcoin,bitcoin,2010-07-13 00:00:00+00:00,21000000.00000,False
1,1027,ETH,Ethereum,ethereum,2015-08-07 00:00:00+00:00,NaN,True
2,1839,BNB,BNB,bnb,2017-07-25 00:00:00+00:00,136358610.77000,False
3,5426,SOL,Solana,solana,2020-04-10 00:00:00+00:00,NaN,True
4,52,XRP,XRP,xrp,2013-08-04 00:00:00+00:00,100000000000.00000,False
5,74,DOGE,Dogecoin,dogecoin,2013-12-15 00:00:00+00:00,NaN,True
6,2010,ADA,Cardano,cardano,2017-10-01 00:00:00+00:00,45000000000.00000,False
7,1958,TRX,TRON,tron,2017-09-13 00:00:00+00:00,NaN,True
8,5805,AVAX,Avalanche,avalanche,2020-07-13 00:00:00+00:00,715748719.00000,False
9,11419,TON,Toncoin,toncoin,2021-08-26 13:40:22+00:00,NaN,True
10,1975,LINK,Chainlink,chainlink,2017-09-20 00:00:00+00:00,1000000000.00000,False
11,5994,SHIB,Shiba Inu,shiba-inu,2020-08-01 00:00:00+00:00,589552695333683.00000,False
12,6636,DOT,Polkadot,polkadot-new,2020-08-19 00:00:00+00:00,2100000000.00000,False
13,28321,POL,Polygon (prev. MATIC),polygon-ecosystem-token,2023-10-30 14:43:57+00:00,NaN,False
14,2,LTC,Litecoin,litecoin,2013-04-28 00:00:00+00:00,84000000.00000,False
15,1831,BCH,Bitcoin Cash,bitcoin-cash,2017-07-23 00:00:00+00:00,21000000.00000,False
16,7083,UNI,Uniswap,uniswap,2020-09-17 00:00:00+00:00,NaN,False
17,6535,NEAR,NEAR Protocol,near-protocol,2020-08-11 00:00:00+00:00,NaN,False
18,512,XLM,Stellar,stellar,2014-08-05 00:00:00+00:00,50001806812.00000,False
19,3794,ATOM,Cosmos,cosmos,2019-03-14 00:00:00+00:00,NaN,True

In [32]:
fact_coin_prices = df2[['timestamp', 'date', 'id', 'cmc_rank', 'circulating_supply', 
                       'total_supply', 'aud_price', 'aud_volume_24h', 'aud_cex_volume_24h',
                       'aud_dex_volume_24h', 'aud_volume_change_24h', 'aud_percent_change_1h', 'aud_percent_change_24h',
                       'aud_percent_change_7d', 'aud_percent_change_30d', 'aud_percent_change_60d',
                       'aud_percent_change_90d', 'aud_market_cap', 'aud_market_cap_dominance',
                       'aud_fully_diluted_market_cap']].copy()
fact_coin_prices

,timestamp,date,id,cmc_rank,circulating_supply,total_supply,aud_price,aud_volume_24h,aud_cex_volume_24h,aud_dex_volume_24h,aud_volume_change_24h,aud_percent_change_1h,aud_percent_change_24h,aud_percent_change_7d,aud_percent_change_30d,aud_percent_change_60d,aud_percent_change_90d,aud_market_cap,aud_market_cap_dominance,aud_fully_diluted_market_cap
0,2026-03-04 15:17:25.859452,2026-03-04,1,1,19997556.00000,19997556.00000,96735.57477,71408978199.96277,71316216306.00313,92761893.95963,-9.04010,-0.72278,-0.77190,3.70805,-10.33698,-24.82912,-27.42951,1934475073603.52881,58.50700,2031447070115.66895
1,2026-03-04 15:17:25.859452,2026-03-04,1027,2,120692150.42008,120692150.42008,2796.42258,34166070694.01336,33880054535.02634,286016158.98703,-7.00380,-0.80569,-2.42720,2.93437,-11.42640,-37.14766,-38.97059,337506255159.08789,10.20770,337506255159.08539
2,2026-03-04 15:17:25.859452,2026-03-04,1839,4,136358607.97000,136358607.97000,898.21147,2469415553.20012,2408006599.21917,61408953.98095,-11.27800,-0.51777,-0.94517,6.12786,-15.39574,-28.26643,-31.41364,122478865119.41614,3.70430,122478867634.41240
3,2026-03-04 15:17:25.859452,2026-03-04,5426,7,569767412.47295,621598902.25483,122.02744,7071298463.57905,7071245003.01036,53460.56868,-7.69670,-1.31215,-0.80363,4.49094,-13.48513,-35.41650,-40.82610,69527256866.16490,2.10280,75852120705.22375
4,2026-03-04 15:17:25.859452,2026-03-04,52,5,61090376977.00000,99985708785.00000,1.93051,3951698504.51614,3948117678.23354,3580826.28260,-15.96580,-0.42805,-1.31732,-1.08594,-13.27256,-33.75805,-38.37629,117935545265.14607,3.56690,193050937154.22971
5,2026-03-04 15:17:25.859452,2026-03-04,74,9,168976693126.57907,168976693126.57907,0.12787,1942838715.68337,1940505639.56064,2333076.12273,13.15560,-0.21344,-2.71719,-2.92551,-12.17724,-37.44835,-40.73003,21607698475.30287,0.65350,21607698475.30228
6,2026-03-04 15:17:25.859452,2026-03-04,2010,10,36078864112.21547,44994838422.19901,0.37487,1023210430.59812,1021600225.54065,1610205.05747,16.86810,-0.51041,-3.66537,-0.99463,-7.02513,-33.83297,-41.61222,13524752977.60850,0.40870,16868986842.25084
7,2026-03-04 15:17:25.859452,2026-03-04,1958,8,94741680902.06120,94741679182.29910,0.39968,683163318.14398,683036461.18220,126856.96179,7.32450,0.03415,-0.99555,-2.19351,-0.69052,-2.89224,0.05783,37866534789.04951,1.14420,37866534101.69299
8,2026-03-04 15:17:25.859452,2026-03-04,5805,24,431771961.17721,463441061.17721,13.09211,441948850.18211,436722398.56245,5226451.61966,-16.15550,-0.18579,0.22379,7.85238,-5.71084,-35.02324,-37.66831,5652806914.86031,0.17100,9370662460.42700
9,2026-03-04 15:17:25.859452,2026-03-04,11419,29,2452742484.70281,5155755757.91270,1.78729,134422473.79311,131723916.98682,2698556.80629,-11.64700,-0.06803,1.48880,-3.33217,-5.02890,-31.10600,-23.37399,4383750696.27567,0.13260,9214806704.96542
10,2026-03-04 15:17:25.859452,2026-03-04,1975,15,708099970.45259,1000000000.00000,12.48464,1085378595.40069,1073778146.52775,11600448.87294,-10.43890,-0.74731,-1.48541,2.96362,-5.14862,-33.98261,-40.00925,8840371143.68487,0.26740,12484637074.67378
11,2026-03-04 15:17:25.859452,2026-03-04,5994,27,589243742059209.87500,589500284160680.12500,0.00001,225885557.31944,225713229.93626,172327.38318,0.74090,-0.49392,0.28527,-8.71921,-17.41392,-32.84471,-38.72489,4579128959.38493,0.13850,4581529896.01893
12,2026-03-04 15:17:25.859452,2026-03-04,6636,32,1671149579.01020,1671149579.01020,2.17477,269692017.18602,269219294.16939,472723.01663,-28.56330,-0.67303,2.03865,20.03238,2.64410,-29.09346,-34.85214,3634370740.21528,0.10990,4567022994.41909
13,2026-03-04 15:17:25.859452,2026-03-04,28321,52,10601927073.04602,10601927083.04602,0.14496,111352130.80320,111019243.51493,332887.28826,-30.63480,0.11938,1.35397,-10.82144,-0.35738,-12.16613,-20.79093,1536815811.95159,0.04650,1536815813.40603
14,2026-03-04 15:17:25.859452,2026-03-04,2,22,76911876.98347,84000000.00000,77.97232,514727990.96060,513948325.66921,779665.29140,-8.91200,-0.64450,1.09649,4.13706,-5.07643,-33.71221,-36.49335,5996997695.79299,0.18120,6549675111.35891
15,2026-03-04 15:17:25.859452,2026-03-04,1831,11,20002471.87500,20002471.87500,631.00367,457234012.66398,454482739.68761,2751272.97637,-20.44600,-0.16463,-0.32374,-11.37505,-12.53143,-29.40867,-25.40281,12621633131.00621,0.38170,13251077037.25840
16,2026-03-04 15:17:25.859452,2026-03-04,7083,34,633795562.74653,898430420.03663,5.57002,379953207.95676,377160959.35384,2792248.60292,-11.25100,-1.14488,0.02038,12.35437,2.86606,-35.36399,-36.52662,3530252521.66766,0.10680,5004273368.73867
17,2026-03-04 15:17:25.859452,2026-03-04,6535,38,1289252866.00000,1289252866.00000,1.96560,749855084.74420,749747791.57730,107293.16690,-24.73070,-1.35311,-2.01308,39.88336,18.40269,-18.95410,-26.32402,2534154274.75764,0.07660,2534154274.75630
18,2026-03-04 15:17:25.859452,2026-03-04,512,19,32985091890.39495,50001786883.65895,0.21542,170900335.64657,170703558.77531,196776.87127,-5.17950,-0.53570,-1.20406,-1.37330,-11.98140,-33.24961,-41.14023,7105787616.66366,0.21490,10771600116.69354
19,2026-03-04 15:17:25.859452,2026-03-04,3794,58,496027140.00000,496027140.00000,2.59759,90471899.33154,89611766.41084,860132.92070,4.07500,-0.50353,-1.22899,-11.47884,-4.41774,-18.23344,-22.96968,1288475970.52049,0.03900,1288475970.51600
20,2026-03-04 15:33:37.459146,2026-03-04,1,1,19997556.00000,19997556.00000,96552.86922,72165689782.21178,72070065418.18173,95624364.03005,-8.18660,-0.36368,-1.16650,2.98870,-11.30816,-25.13005,-27.72371,1930821409237.68530,58.41500,2027610253672.56689
21,2026-03-04 15:33:37.459146,2026-03-04,1027,2,120692150.42008,120692150.42008,2789.81573,34651795211.19971,34364803756.14609,286991455.05367,-6.16290,-0.63329,-2.88419,2.04568,-13.51082,-37.44780,-39.18115,336708859634.23340,10.18680,336708859634.23602
22,2026-03-04 15:33:37.459146,2026-03-04,1839,4,136358607.97000,136358607.97000,897.59912,2474067885.46636,2412629851.99782,61438033.46853,-11.24710,-0.53738,-1.26516,5.54397,-17.09371,-28.52610,-31.46384,122395366905.22009,3.70290,122395366905.21877
23,2026-03-04 15:33:37.459146,2026-03-04,5426,7,569767412.47295,621598902.25483,121.54663,7109423401.67548,7109369745.76350,53655.91198,-7.21900,-1.33288,-1.31505,3.51373,-15.95147,-35.82076,-41.07017,69253307557.59845,2.09520,75553250349.09154
24,2026-03-04 15:33:37.459146,2026-03-04,52,5,61090376977.00000,99985708785.00000,1.92513,3963346480.59590,3959751261.84582,3595218.75007,-15.78780,-0.66218,-1.73568,-1.64594,-15.43633,-34.38589,-38.64797,117606909570.51424,3.55810,192512987135.09631
25,2026-03-04 15:33:37.459146,2026-03-04,74,9,168976693126.57907,168976693126.57907,0.12734,1948491029.86066,1946157091.21924,2333938.64143,13.26370,-0.51107,-3.32852,-3.71517,-14.80217,-37.95151,-41.00904,21518250606.08009,0.65100,21518250606.07780
26,2026-03-04 15:33:37.459146,2026-03-04,2010,10,36078864112.21547,44994838422.19901,0.37155,1046670754.24059,1044746266.72780,1924487.51279,19.38450,-1.32284,-4.64945,-2.27539,-9.79499,-34.59714,-42.10078,13404947461.28085,0.40550,16719557297.63413
27,2026-03-04 15:33:37.459146,2026-03-04,1958,8,94741680902.06120,94741679182.29910,0.40038,683744932.85289,683614857.51488,130075.33801,7.47440,0.01667,-1.01818,-2.26908,-1.09568,-2.92260,-0.07766,37932723566.15255,1.14730,37932722877.58788
28,2026-03-04 15:33:37.459146,2026-03-04,5805,24,431771961.17721,463441061.17721,12.99103,448030337.79860,442749951.78203,5280386.01657,-15.04130,-0.90035,-0.73136,6.61297,-8.78314,-35.47770,-38.28552,5609162539.08342,0.16970,9298313144.43635
29,2026-03-04 15:33:37.459146,2026-03-04,11419,29,2452742484.70281,5155755757.91270,1.79115,134200304.99876,131481010.08748,2719294.91128,-11.98510,0.25803,1.26042,-3.65665,-6.84176,-30.98298,-23.24618,4393238987.99596,0.13290,9234751446.39246
30,2026-03-04 15:33:37.459146,2026-03-04,1975,15,708099970.45259,1000000000.00000,12.45382,1087771531.39051,1076156417.84541,11615113.54510,-10.77900,-0.58007,-1.82753,2.28946,-7.80305,-34.28949,-40.22114,8818549661.55286,0.26680,12453820123.61888
31,2026-03-04 15:33:37.459146,2026-03-04,5994,27,589243742059209.87500,589500284160680.12500,0.00001,225438719.45219,225264001.55842,174717.89377,0.10070,-0.34067,-0.01340,-9.05797,-19.58367,-33.14873,-38.83004,4577439586.16873,0.13850,4579839637.03185
32,2026-03-04 15:33:37.459146,2026-03-04,6636,33,1671149579.01020,1671149579.01020,2.15979,270141730.95963,269661177.69023,480553.26941,-28.51080,-1.33508,0.79220,18.81484,-0.14598,-29.68066,-35.44611,3609331854.78787,0.10920,4535558629.96914
33,2026-03-04 15:33:37.459146,2026-03-04,28321,52,10601927073.04602,10601927083.04602,0.14442,111071174.92782,110733624.32582,337550.60200,-30.95680,-0.41269,0.81700,-10.82773,-2.70339,-12.79769,-21.23758,1531176971.28728,0.04630,1531176972.73322
34,2026-03-04 15:33:37.459146,2026-03-04,2,22,76911876.98347,84000000.00000,77.81918,510797620.71752,510025722.15240,771898.56512,-10.65440,-0.43573,0.68456,3.46085,-7.10885,-34.03411,-36.66857,5985219356.52249,0.18100,6536811291.90812
35,2026-03-04 15:33:37.459146,2026-03-04,1831,11,20002471.87500,20002471.87500,629.11025,461426623.29475,458721935.22191,2704688.07283,-19.87480,-0.55639,-0.78416,-12.00253,-14.63883,-29.82129,-25.81386,12583760165.24960,0.38070,13211315337.50734
36,2026-03-04 15:33:37.459146,2026-03-04,7083,34,633795562.74653,898430420.03663,5.54551,380298860.01290,377478697.71302,2820162.29988,-11.46810,-1.36327,-0.25102,11.39790,0.40332,-35.80420,-36.84570,3514721882.42461,0.10630,4982258069.86439
37,2026-03-04 15:33:37.459146,2026-03-04,6535,39,1289252866.00000,1289252866.00000,1.95521,742514704.59182,742408144.05387,106560.53795,-26.61890,-1.83658,-3.03610,38.83650,15.03664,-19.45944,-26.78734,2520754483.97303,0.07630,2520754483.97458
38,2026-03-04 15:33:37.459146,2026-03-04,512,19,32985091890.39495,50001786883.65895,0.21462,171409204.29173,171212430.89208,196773.39965,-4.76120,-0.73463,-1.59880,-1.98272,-14.17518,-33.92830,-41.54704,7079423349.24060,0.21420,10731634758.67369
39,2026-03-04 15:33:37.459146,2026-03-04,3794,58,496027140.00000,496027140.00000,2.59648,90753356.53906,89890885.25129,862471.28777,4.73280,-0.13023,-1.44780,-11.71862,-6.70537,-18.23401,-22.94615,1287925211.18762,0.03900,1287925211.19350
40,2026-03-05 21:11:25.610511,2026-03-05,1,1,19998093.00000,19998093.00000,103210.17145,94493360657.60916,94354786011.04053,138574646.56862,13.11870,0.19059,1.27108,5.96979,-7.31293,-20.48801,-20.34388,2064006607193.74048,59.31290,2167413600440.22412
41,2026-03-05 21:11:25.610511,2026-03-05,1027,2,120692108.97550,120692108.97550,3017.87565,42969707717.44983,42679348919.15477,290358798.29508,13.44870,-0.09452,1.89110,2.23553,-7.38556,-32.37498,-32.10901,364233776327.08362,10.46690,364233776327.08014
42,2026-03-05 21:11:25.610511,2026-03-05,1839,4,136358541.80000,136358541.80000,930.94158,2941378995.85273,2870340283.30405,71038712.54869,17.76600,0.36721,0.67058,4.18929,-15.04121,-25.99405,-26.52812,126941836048.49052,3.64790,126941836048.49216
43,2026-03-05 21:11:25.610511,2026-03-05,5426,7,569763750.35215,621597889.30619,129.42648,8418498748.48993,8418465601.40995,33147.07998,2.19820,0.17249,0.67527,3.07283,-11.46051,-32.22800,-33.23817,73742519349.86484,2.11910,80451229745.07330
44,2026-03-05 21:11:25.610511,2026-03-05,52,5,61090376977.00000,99985708785.00000,2.02569,5492231911.98338,5485860285.32513,6371626.65825,19.37370,0.31626,0.81408,-1.81820,-11.07186,-31.47696,-30.79223,123750191713.30658,3.55620,202569042518.59460
45,2026-03-05 21:11:25.610511,2026-03-05,74,9,153281356383.70526,153281356383.70526,0.13658,3526169605.99186,3522774807.60219,3394798.38967,67.78700,-0.05691,3.80409,-3.82915,-10.37880,-36.94145,-33.51688,20935884872.73642,0.60160,20935884872.74154
46,2026-03-05 21:11:25.610511,2026-03-05,2010,10,36078864112.21547,44994838422.19901,0.38743,1213185567.38908,1210487448.26423,2698119.12485,3.92420,0.03049,-0.15531,-7.34703,-7.96461,-32.39162,-36.76844,13978036769.61574,0.40150,17434353051.58833
47,2026-03-05 21:11:25.610511,2026-03-05,1958,8,94742233291.64661,94742236559.05589,0.40369,904911386.23651,904734408.96988,176977.26663,11.81520,0.01864,0.10904,-0.70700,0.29968,-3.12517,-0.27775,38246338706.96476,1.09870,38246340025.98069
48,2026-03-05 21:11:25.610511,2026-03-05,5805,24,431771961.17721,463441061.17721,13.42383,561722485.61436,556568390.38789,5154095.22648,3.51390,-0.05236,0.64677,0.74615,-6.12419,-32.76250,-32.44563,5796032471.56999,0.16660,9608087578.21825
49,2026-03-05 21:11:25.610511,2026-03-05,11419,28,2452840181.38496,5155871705.21176,1.91036,147797787.93935,143860108.20056,3937679.73879,19.25310,-0.09859,3.18548,3.73059,-1.72579,-27.27248,-15.07545,4685801802.03918,0.13470,9849558528.39800
50,2026-03-05 21:11:25.610511,2026-03-05,1975,15,708099970.45259,1000000000.00000,13.17948,1261734006.86773,1255308204.90907,6425801.95866,8.17030,-0.08036,0.49183,-0.19543,-3.46016,-30.65760,-34.05964,9332391210.07386,0.26820,13179482558.24609
51,2026-03-05 21:11:25.610511,2026-03-05,5994,27,589243742059209.87500,589500284160680.12500,0.00001,212469989.42155,212141210.75157,328778.66999,-2.25160,0.07803,0.77902,-8.51997,-17.17542,-35.42377,-33.34899,4719131377.22606,0.13560,4721605720.15864
52,2026-03-05 21:11:25.610511,2026-03-05,6636,32,1671583119.10533,1671583119.10533,2.16960,264623931.78893,264254685.27371,369246.51521,-8.41200,-0.69679,-1.77812,-5.86395,0.59268,-28.95621,-31.89508,3626662044.59302,0.10420,4556154107.19859
53,2026-03-05 21:11:25.610511,2026-03-05,28321,52,10602502283.19926,10602502293.19926,0.14603,121793293.66014,121576202.76250,217090.89764,13.29060,0.08687,-1.20943,-7.37700,-12.33504,-14.13805,-16.37578,1548302337.72996,0.04450,1548302339.18970
54,2026-03-05 21:11:25.610511,2026-03-05,2,21,76916283.23347,84000000.00000,80.38709,561006230.07339,560187133.06346,819097.00993,1.09830,0.15686,0.91412,0.51067,-5.30208,-31.39939,-31.14635,6183076071.01514,0.17760,6752515437.96999
55,2026-03-05 21:11:25.610511,2026-03-05,1831,11,20003034.37500,20003034.37500,658.03509,609340798.12099,606425141.84229,2915656.27870,11.80120,0.52594,0.84582,-7.67176,-12.23025,-28.62356,-18.38583,13162698539.07122,0.37830,13818736904.53612
56,2026-03-05 21:11:25.610511,2026-03-05,7083,34,633755562.74653,898390420.03663,5.68256,421506618.30537,418282133.16959,3224485.13578,-0.57500,-0.49451,-1.31837,-0.94157,2.76256,-32.40124,-31.28908,3601353112.03131,0.10350,5105156191.45117
57,2026-03-05 21:11:25.610511,2026-03-05,6535,43,1289383171.00000,1289383171.00000,1.84065,437119976.98860,437061363.58907,58613.39954,-27.14860,-1.74419,-6.47456,14.15121,8.64949,-24.76189,-25.31672,2373308659.10853,0.06820,2373308659.10814
58,2026-03-05 21:11:25.610511,2026-03-05,512,19,32985990215.50566,50001786883.65895,0.22535,210142462.72980,209757620.33375,384842.39604,10.75940,0.00490,1.61277,-3.71245,-10.20940,-31.88081,-36.45422,7433346549.82982,0.21360,11267836912.66281
59,2026-03-05 21:11:25.610511,2026-03-05,3794,58,496198300.00000,496198300.00000,2.66117,79249197.15094,78196996.27390,1052200.87704,-17.43100,0.06993,-1.22648,-2.84561,-6.03760,-18.20461,-17.53338,1320466882.13788,0.03790,1320466882.14325

In [33]:
fact_global_market = df2[['timestamp', 'date', 'global_btc_dominance', 'global_eth_dominance',
                          'global_defi_volume_24h', 'global_defi_market_cap',
                          'global_stablecoin_volume_24h', 'global_stablecoin_market_cap',
                          'global_derivatives_volume_24h']]
fact_global_market = fact_global_market.drop_duplicates(subset=['timestamp', 'date'])
fact_global_market

,timestamp,date,global_btc_dominance,global_eth_dominance,global_defi_volume_24h,global_defi_market_cap,global_stablecoin_volume_24h,global_stablecoin_market_cap,global_derivatives_volume_24h
0,2026-03-04 15:17:25.859452,2026-03-04,58.48246,10.20420,10974994536.52728,57157748549.36966,113795314423.37778,287344319485.56274,1081072494741.13416
20,2026-03-04 15:33:37.459146,2026-03-04,58.45671,10.19934,10993153719.67540,56941053091.26615,114105291541.96266,287352851069.97534,1083701578301.22717
40,2026-03-05 21:11:25.610511,2026-03-05,59.22961,10.45240,11752110256.91377,59157329833.95812,141247950275.02368,288031251844.70331,1126200969683.01538

In [34]:
dim_date = df2[['date']]
dim_date = dim_date.drop_duplicates()
dim_date['year'] = dim_date['date'].dt.year
dim_date['quarter'] = dim_date['date'].dt.quarter
dim_date['month'] = dim_date['date'].dt.month
dim_date['day'] = dim_date['date'].dt.day
dim_date['month_name'] = dim_date['date'].dt.month_name()
dim_date['week'] = dim_date['date'].dt.isocalendar().week
dim_date['day_of_week'] = dim_date['date'].dt.dayofweek
dim_date['day_name'] = dim_date['date'].dt.day_name()

In [35]:
dim_date

,date,year,quarter,month,day,month_name,week,day_of_week,day_name
0,2026-03-04,2026,1,3,4,March,10,2,Wednesday
40,2026-03-05,2026,1,3,5,March,10,3,Thursday

In [37]:
(BASE_DIR / 'output/tables').mkdir(parents=True, exist_ok=True)

dim_coin.to_csv(BASE_DIR / 'output/tables/dim_coin.csv', index=False, encoding='utf-8-sig', float_format='%.5f')
dim_date.to_csv(BASE_DIR / 'output/tables/dim_date.csv', index=False, encoding='utf-8-sig', float_format='%.5f')
fact_coin_prices.to_csv(BASE_DIR / 'output/tables/fact_coin_prices.csv', index=False, encoding='utf-8-sig', float_format='%.5f')
fact_global_market.to_csv(BASE_DIR / 'output/tables/fact_global_market.csv', index=False, encoding='utf-8-sig', float_format='%.5f')